name: 'Terraform AKS Deployment'

on:
  push:
    branches:
      - demo
    paths:
      - 'Terraform/azure/demo/**'
      - '.github/workflows/aks-deploy.yaml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terraform:
    name: 'Terraform Plan and Apply/Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform/azure/demo
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply on push, or if workflow_dispatch input is 'apply'
    - name: Terraform Apply
      if: github.ref == 'refs/heads/demo' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
      run: terraform apply -auto-approve -input=false

    # Destroy only if workflow_dispatch input is 'destroy'
    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve -input=false
