name: Hello Workflow

on: [push] 

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo "This is step one"
      - name: Step two
        run: echo "This is step two"
