name: Terraform Cloud Apply

on:
  push:
    branches: [main] # or your deployment branch

jobs:
  run-terraform-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Terraform Cloud Run
        uses: hashicorp/tfc-workflows-github-actions@v1
        with:
          organization: your-tfc-org    # <- your Terraform Cloud org name
          workspace: your-tfc-workspace # <- your workspace name
          tfc_token: ${{ secrets.TFC_TOKEN }}
          # Optional: auto-apply if you want:
          auto_apply: true
