- name: Trigger TFC Run via API
  env:
    TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
    TFC_ORG: techrip              # <-- replace with your TFC org
    TFC_WORKSPACE: demo  # <-- replace with your TFC workspace
  run: |
    curl -s \
      --header "Authorization: Bearer $TFC_TOKEN" \
      --header "Content-Type: application/vnd.api+json" \
      --request POST \
      --data @- \
      https://app.terraform.io/api/v2/organizations/$TFC_ORG/runs <<EOF
    {
      "data": {
        "attributes": {
          "is-destroy": false,
          "message": "Triggered by GitHub Actions"
        },
        "type": "runs",
        "relationships": {
          "workspace": {
            "data": {
              "type": "workspaces",
              "name": "$TFC_WORKSPACE"
            }
          }
        }
      }
    }
    EOF
